server:
  context-path: /api
  port: 8080
  compression:
    enabled: true
    mime-types: application/json,application/xml,text/html,text/xml,text/plain

application:
  path-mapper:
    rajithd-aurea/vobs_blr: /vobs/blr/
  clear-case:
    view-name: rdelantha
    server:
      ip:
      username:
      password:
