server:
  context-path: /api
  port: 8080
  compression:
    enabled: true
    mime-types: application/json,application/xml,text/html,text/xml,text/plain

application:
  clear-case:
    property-file: ${GIT_CC_PATH_MAPPER_FILE}
    view-name: ${GIT_CC_CLEARCASE_VIEW_NAME}
    server:
      hostname: ${GIT_CC_CLEARCASE_HOSTNAME}
      username: ${GIT_CC_CLEARCASE_USERNAME}
      password: ${GIT_CC_CLEARCASE_PASSWORD}
      workspace: /tmp/git-cc-bridge/
  git-server:
    username:
    password:
    workspace: /tmp/git-cc-bridge/

logging:
  file: git-cc-bridge.log
