server:
  context-path: /api
  port: 8080
  compression:
    enabled: true
    mime-types: application/json,application/xml,text/html,text/xml,text/plain

application:
  clear-case:
    view-name: rdelantha
    server:
      hostname:
      username:
      password:
      workspace: /tmp/
  git-server:
    username:
    password:
    workspace: /tmp/
